import '@radix-ui/themes/styles.css';
import './theme-config.css';
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Swanky_and_Moo_Moo } from "next/font/google";
import NavBar from "@/lib/components/navbar/navbar";
import { Theme, ThemePanel } from '@radix-ui/themes';

const inter = Inter({ 
  subsets: ["latin"],
  display:'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "Issue tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={inter.variable}
      >
        <Theme accentColor="violet">
          <NavBar />
          <main className=' p-5'>
            {children}
          </main>
          {/* <ThemePanel/> */}
        </Theme>
      </body>
    </html>
  );
}
